Add debugging to scirpt

diff --git a/.chezmoiscripts/run_once_after_install-20-nix.sh.tmpl b/.chezmoiscripts/run_once_after_install-20-nix.sh.tmpl
--- a/.chezmoiscripts/run_once_after_install-20-nix.sh.tmpl
+++ b/.chezmoiscripts/run_once_after_install-20-nix.sh.tmpl
@@ -2,7 +2,8 @@
 
 #!/bin/bash
 
-# Define your configuration here
+set -x
+
 read -r -d '' CONFIG << EOM
 # Generated by https://github.com/DeterminateSystems/nix-installer, version 0.8.0.
 bash-prompt-prefix = (nix:$name)\040
@@ -15,26 +16,16 @@ auto-optimise-store = true
 trusted-users = root zerodeth
 EOM
 
-# Check if the /etc/nix/nix.conf file exists
-if [ ! -f "/etc/nix/nix.conf" ]; then
-    echo "/etc/nix/nix.conf does not exist. Creating a new one..."
-    sudo touch /etc/nix/nix.conf
-fi
-
-# Check if the configuration already exists in the file
-if grep -Fxq "$CONFIG" /etc/nix/nix.conf
-then
-    echo "Configuration already exists."
-else
-    # Append configuration to the /etc/nix/nix.conf file and restart the service
-    echo "$CONFIG" | awk '{$1=$1};1' | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
-
-    if [ $? -eq 0 ]
+if [ -f "/etc/nix/nix.conf" ]; then
+    if ! grep -Fxq "$CONFIG" /etc/nix/nix.conf
     then
-        echo "Configuration appended successfully and nix-daemon terminated."
+        echo "$CONFIG" | awk '{$1=$1};1' | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
+        if [ $? -eq 0 ]; then echo "Success"; else echo "Failed"; fi
     else
-        echo "Failed to append configuration."
+        echo "Configuration already present"
     fi
+else
+    echo "/etc/nix/nix.conf does not exist. Please create one..."
 fi
 
 {{ end -}}
